// <auto-generated />
namespace BookShopSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelatedBooksTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelatedBooksTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201611141443447_RelatedBooksTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
